name: first_flow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello Tabrez!"
      - name: Farewell
        run: echo "Bye Bye"

